echo "We are trying this practical from linux EC2"
echo "I am from Young minds"
echo "We are from batch-27" 
echo "I am learning Git/Github"
echo "I have added new code"
echo "I am Bhavana Choudhari"
echo "I am Bhavana Choudhari changes in B2"
